// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	fizzbuzz "github.com/houssemlou/fizz/internal/domain/fizzbuzz"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Record provides a mock function with given fields: ctx, p, requestID
func (_m *MockRepository) Record(ctx context.Context, p fizzbuzz.Params, requestID string) error {
	ret := _m.Called(ctx, p, requestID)

	if len(ret) == 0 {
		panic("no return value specified for Record")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, fizzbuzz.Params, string) error); ok {
		r0 = rf(ctx, p, requestID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Record_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Record'
type MockRepository_Record_Call struct {
	*mock.Call
}

// Record is a helper method to define mock.On call
//   - ctx context.Context
//   - p fizzbuzz.Params
//   - requestID string
func (_e *MockRepository_Expecter) Record(ctx interface{}, p interface{}, requestID interface{}) *MockRepository_Record_Call {
	return &MockRepository_Record_Call{Call: _e.mock.On("Record", ctx, p, requestID)}
}

func (_c *MockRepository_Record_Call) Run(run func(ctx context.Context, p fizzbuzz.Params, requestID string)) *MockRepository_Record_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(fizzbuzz.Params), args[2].(string))
	})
	return _c
}

func (_c *MockRepository_Record_Call) Return(_a0 error) *MockRepository_Record_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Record_Call) RunAndReturn(run func(context.Context, fizzbuzz.Params, string) error) *MockRepository_Record_Call {
	_c.Call.Return(run)
	return _c
}

// Top provides a mock function with given fields: ctx
func (_m *MockRepository) Top(ctx context.Context) (*fizzbuzz.TopResult, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Top")
	}

	var r0 *fizzbuzz.TopResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*fizzbuzz.TopResult, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *fizzbuzz.TopResult); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*fizzbuzz.TopResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Top_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Top'
type MockRepository_Top_Call struct {
	*mock.Call
}

// Top is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) Top(ctx interface{}) *MockRepository_Top_Call {
	return &MockRepository_Top_Call{Call: _e.mock.On("Top", ctx)}
}

func (_c *MockRepository_Top_Call) Run(run func(ctx context.Context)) *MockRepository_Top_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_Top_Call) Return(_a0 *fizzbuzz.TopResult, _a1 error) *MockRepository_Top_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Top_Call) RunAndReturn(run func(context.Context) (*fizzbuzz.TopResult, error)) *MockRepository_Top_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
