// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	fizzbuzz "github.com/houssemlou/fizz/internal/domain/fizzbuzz"

	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function with given fields: ctx, p
func (_m *MockService) Generate(ctx context.Context, p fizzbuzz.Params) ([]string, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, fizzbuzz.Params) ([]string, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, fizzbuzz.Params) []string); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, fizzbuzz.Params) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockService_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - ctx context.Context
//   - p fizzbuzz.Params
func (_e *MockService_Expecter) Generate(ctx interface{}, p interface{}) *MockService_Generate_Call {
	return &MockService_Generate_Call{Call: _e.mock.On("Generate", ctx, p)}
}

func (_c *MockService_Generate_Call) Run(run func(ctx context.Context, p fizzbuzz.Params)) *MockService_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(fizzbuzz.Params))
	})
	return _c
}

func (_c *MockService_Generate_Call) Return(_a0 []string, _a1 error) *MockService_Generate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_Generate_Call) RunAndReturn(run func(context.Context, fizzbuzz.Params) ([]string, error)) *MockService_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// Top provides a mock function with given fields: ctx
func (_m *MockService) Top(ctx context.Context) (*fizzbuzz.TopResult, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Top")
	}

	var r0 *fizzbuzz.TopResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*fizzbuzz.TopResult, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *fizzbuzz.TopResult); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*fizzbuzz.TopResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_Top_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Top'
type MockService_Top_Call struct {
	*mock.Call
}

// Top is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) Top(ctx interface{}) *MockService_Top_Call {
	return &MockService_Top_Call{Call: _e.mock.On("Top", ctx)}
}

func (_c *MockService_Top_Call) Run(run func(ctx context.Context)) *MockService_Top_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_Top_Call) Return(_a0 *fizzbuzz.TopResult, _a1 error) *MockService_Top_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_Top_Call) RunAndReturn(run func(context.Context) (*fizzbuzz.TopResult, error)) *MockService_Top_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
