// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	fizzbuzz "github.com/houssemlou/fizz/internal/domain/fizzbuzz"
	mock "github.com/stretchr/testify/mock"
)

// MockEventRecorder is an autogenerated mock type for the EventRecorder type
type MockEventRecorder struct {
	mock.Mock
}

type MockEventRecorder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventRecorder) EXPECT() *MockEventRecorder_Expecter {
	return &MockEventRecorder_Expecter{mock: &_m.Mock}
}

// Record provides a mock function with given fields: ctx, p
func (_m *MockEventRecorder) Record(ctx context.Context, p fizzbuzz.Params) error {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Record")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, fizzbuzz.Params) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEventRecorder_Record_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Record'
type MockEventRecorder_Record_Call struct {
	*mock.Call
}

// Record is a helper method to define mock.On call
//   - ctx context.Context
//   - p fizzbuzz.Params
func (_e *MockEventRecorder_Expecter) Record(ctx interface{}, p interface{}) *MockEventRecorder_Record_Call {
	return &MockEventRecorder_Record_Call{Call: _e.mock.On("Record", ctx, p)}
}

func (_c *MockEventRecorder_Record_Call) Run(run func(ctx context.Context, p fizzbuzz.Params)) *MockEventRecorder_Record_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(fizzbuzz.Params))
	})
	return _c
}

func (_c *MockEventRecorder_Record_Call) Return(_a0 error) *MockEventRecorder_Record_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventRecorder_Record_Call) RunAndReturn(run func(context.Context, fizzbuzz.Params) error) *MockEventRecorder_Record_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEventRecorder creates a new instance of MockEventRecorder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventRecorder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventRecorder {
	mock := &MockEventRecorder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
