apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fizzbuzz.name" . }}
  labels:
    {{- include "fizzbuzz.labels" . | nindent 4 }}
type: Opaque
stringData:
  API_KEY:      {{ .Values.secrets.apiKey | quote }}
  DATABASE_URL: {{ .Values.secrets.databaseURL | quote }}
  KAFKA_BROKER: {{ .Values.secrets.kafkaBroker | quote }}
